import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ScanLine, Upload } from 'lucide-react';
import { createCustomer } from '../services/operations';

export function CustomerCreatePage() {
  const navigate = useNavigate(); const [file, setFile] = useState<File>(); const [error, setError] = useState(''); const ocrConfigured = Boolean(import.meta.env.VITE_OCR_PROVIDER_ENABLED === 'true');
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); try { await createCustomer({ first_name: String(form.get('first_name')), middle_name: String(form.get('middle_name')) || null, last_name: String(form.get('last_name')), email: String(form.get('email')) || null, phone: String(form.get('phone')), address: String(form.get('address')), id_type: String(form.get('id_type')), id_number_encrypted: String(form.get('id_number')) || null }, file); navigate('/customers'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save customer'); } };
  return <><header className="page-header"><div><h1>Register customer</h1><p>Capture customer information and securely attach a valid identification document.</p></div></header><form className="panel form" onSubmit={submit}><div className="form-section"><h2>Personal information</h2><div className="form-grid"><label>First name<input name="first_name" required /></label><label>Middle name<input name="middle_name" /></label><label>Last name<input name="last_name" required /></label><label>Phone<input name="phone" required /></label><label>Email<input name="email" type="email" /></label><label className="span-2">Address<textarea name="address" required /></label></div></div><div className="form-section"><h2>Identity verification</h2><div className="ocr-note"><ScanLine /><div><strong>{ocrConfigured ? 'OCR extraction available' : 'OCR not configured'}</strong><p>{ocrConfigured ? 'Uploaded fields will be extracted for staff review; nothing is saved automatically.' : 'Continue with manual entry. Your ID upload will still be stored securely.'}</p></div></div><div className="form-grid"><label>ID type<select name="id_type" required><option value="">Choose…</option><option>PhilSys ID</option><option>Driver's License</option><option>Passport</option><option>Other Government ID</option></select></label><label>ID number<input name="id_number" required /></label><label className="upload span-2"><Upload />Upload ID image or PDF<input type="file" accept="image/*,.pdf" required onChange={(event) => setFile(event.target.files?.[0])} /><span>{file?.name ?? 'Choose a private document'}</span></label></div></div>{error && <div className="inline-error">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={() => navigate(-1)}>Cancel</button><button className="primary">Save customer</button></div></form></>;
}
