import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ExternalLink, Search, ShieldCheck } from 'lucide-react';
import { useAuth } from '../auth/AuthProvider';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusChip } from '../components/StatusChip';
import { supabase } from '../lib/supabase';
import type { Database } from '../lib/database.types';

type Application = Database['public']['Tables']['ost_registrations']['Row'];
type Document = Database['public']['Tables']['ost_registration_documents']['Row'];
export function OstApplicationsPage() {
  const { role } = useAuth(); const queryClient = useQueryClient();
  const [documents, setDocuments] = useState<Document[]>([]); const [selected, setSelected] = useState<Application | null>(null); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  const canApprove = role === 'super_admin' || role === 'admin' || role === 'sales_manager';
  const applications = useQuery({ queryKey: ['ost-applications'], queryFn: async () => { const result = await supabase.from('ost_registrations').select('*').order('submitted_at', { ascending: false }); if (result.error) throw result.error; return result.data; } });
  const filtered = useMemo(() => (applications.data ?? []).filter((row) => (!status || row.status === status) && (!search || `${row.first_name} ${row.last_name} ${row.email} ${row.mobile}`.toLowerCase().includes(search.toLowerCase()))), [applications.data, search, status]);
  const open = async (app: Application) => { setSelected(app); setReason(''); const result = await supabase.from('ost_registration_documents').select('*').eq('registration_id', app.id); setDocuments(result.data ?? []); };
  const documentUrl = async (documentId: string) => { const { data } = await supabase.functions.invoke<{ url: string }>('ost-registration', { body: { action: 'document-url', registrationId: selected?.id, documentId } }); if (data?.url) window.open(data.url, '_blank', 'noopener,noreferrer'); else setError('The secure document link could not be created.'); };
  const decide = async (action: 'approve' | 'review', decision?: string) => { if (!selected) return; setError(''); const { error: invokeError } = await supabase.functions.invoke('ost-registration', { body: { action, registrationId: selected.id, status: decision, reason } }); if (invokeError) return setError('The decision could not be saved. For corrections, rejection, or suspension, enter a meaningful reason.'); setSelected(null); await queryClient.invalidateQueries({ queryKey: ['ost-applications'] }); };
  return <><header className="page-header"><div><p className="eyebrow">CONTROLLED ONBOARDING</p><h1>OST applications</h1><p>{role === 'sales_manager' ? 'Review only applications submitted through your referral codes.' : 'Review all OST applications and their validated genealogy placement.'}</p></div><span className="secure-badge"><ShieldCheck /> RLS scoped</span></header>
    <section className="panel"><div className="filters"><label className="search"><Search /><input placeholder="Search name, email, or mobile" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All</option>{['pending_verification','needs_correction','verified','rejected','invited','active','suspended'].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    {applications.isLoading ? <LoadingState /> : applications.error ? <ErrorState message={applications.error.message} retry={() => void applications.refetch()} /> : !filtered.length ? <EmptyState title="No matching applications" body="New applications will appear here after a valid referral submission." /> : <div className="table-wrap"><table><caption className="sr-only">OST applications</caption><thead><tr><th>Applicant</th><th>Submitted</th><th>ID</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><strong>{row.first_name} {row.middle_name} {row.last_name}</strong><small className="table-subtitle">{row.email} · {row.mobile}</small></td><td>{new Date(row.submitted_at).toLocaleDateString()}</td><td>{row.id_type} ••••{row.id_number_last4}</td><td><StatusChip value={row.status} /></td><td><button className="text-button" onClick={() => void open(row)}>Review</button></td></tr>)}</tbody></table></div>}</section>
    {selected ? <div className="dialog-backdrop" role="presentation"><section className="dialog application-dialog" role="dialog" aria-modal="true" aria-label="Review OST application"><div className="panel-heading"><div><p className="eyebrow">IDENTITY REVIEW</p><h2>{selected.first_name} {selected.last_name}</h2></div><StatusChip value={selected.status} /></div><dl><dt>Email</dt><dd>{selected.email}</dd><dt>Mobile</dt><dd>{selected.mobile}</dd><dt>Date of birth</dt><dd>{selected.date_of_birth}</dd><dt>Address</dt><dd>{selected.address_line}, {selected.barangay}, {selected.city}, {selected.province} {selected.postal_code}</dd><dt>ID</dt><dd>{selected.id_type} ending {selected.id_number_last4}</dd></dl><div className="document-actions">{documents.map((document) => <button className="secondary" key={document.id} onClick={() => void documentUrl(document.id)}><ExternalLink /> View ID {document.side}</button>)}</div><label>Decision reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Required for correction, rejection, or suspension" /></label>{error ? <p className="inline-error">{error}</p> : null}<div className="review-actions"><button className="secondary" onClick={() => setSelected(null)}>Close</button>{canApprove && ['pending_verification','needs_correction'].includes(selected.status) ? <><button className="secondary" onClick={() => void decide('review','needs_correction')}>Request correction</button><button className="danger" onClick={() => void decide('review','rejected')}>Reject</button><button className="primary" onClick={() => void decide('approve')}>Approve & invite</button></> : null}{canApprove && ['invited','active'].includes(selected.status) ? <button className="danger" onClick={() => void decide('review','suspended')}>Suspend</button> : null}</div></section></div> : null}
  </>;
}
